DROP table IF EXISTS "user" cascade;
DROP table IF EXISTS "category" cascade;
DROP table IF EXISTS "driver" cascade;
DROP table IF EXISTS "category_question" cascade;
DROP table IF EXISTS "vehicle" cascade;
DROP table IF EXISTS "check_log" cascade;
DROP table IF EXISTS "question" cascade;
DROP table IF EXISTS "signature" cascade;
DROP table IF EXISTS "answer" cascade;